export const commonLabel = {
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot password?",
  signIn: "Sign In",
  dontHaveAccount: "Don't have an account?",
  registerHere: "Register here",
  pleaseSignInToYourAccount: "Please sign in to your account",
  logoutMsg: "Logout successfully",
  totalOrders: "Total Orders",
  pendingOrders: "Pending Orders",
  totalProducts: "Total Products",
  totalCustomers: "Total Customers",
  units: "Units",
  completed: "Completed",
  storeOverview: "Store Overview",
  welcomeBack: "Welcome back!",
  recentActivity: "Recent Activity",
  latestOrders: "Latest",
  orderFrom: "order from",
  productDistribution: "Product Distribution",
  noDistributionDataAvailable: "No distribution data available",
  topCustomer: "Top Customers",
  byTotalPurchaseValue: "By total purchase value",
  noSalesDataFound: "No sales data found",
  categoryName: "Category name",
  categoryDescription: "Category description",
  addCategory: "Add Category",
  updateCategory: "Update Category",
  catalogManagement: "Catalog Management",
  productCategories: "Product Categories",
  organizationManageText: "Organize and manage your store's product structure",
  categoryList: "Categories List",
  categoryDetails: "Category details",
  categoryImage: "Category Image",
  pngJpgUpTo2MB: "PNG, JPG up to 2MB",
  uploading: "Uploading...",
  uploadImage: "Click to upload image",
  deleteCategory: "Delete Category",
  deleteCategoryMsg: "Are you sure you want to delete the category",
  delete: "Delete",
  image: "Image",
  name: "Name",
  description: "Description",
  productName: "Product Name",
  price: "Price",
  addedOn: "Added on",
  inventory: "Inventory",
  productCatalog: "Product Catalog",
  manageText:
    "Manage your store's product inventory, variants, and pricing with precision and ease.",
  status: "Status",
  liveUpdate: "Live Updates",
  addProduct: "Add Product",
  addProductMsg: "Enter the details for your new product catalog item",
  updateProduct: "Update Product",
  generalInfo: "General Information",
  size: "Size",
  stock: "Stock",
  variant: "Variants",
  id: "ID",
  added: "Added",
  comprehensiveOverview: "Comprehensive overview of product and its variants",
  productDetails: "Product Details",
  qty: "Quantity",
  color: "Color",
  variantDescription: "Variant Description",
  variantTitle: "Variant Title",
  variantImage: "Variant Image",
  productVariants: "Product Variants",
  phoneNumber: "Phone Number",
  gender: "Gender",
  userReport: "User Report",
  userReports: "User Reports",
  viewReports: "View Detailed Reports",
  reportDetails:
    "Detailed analysis and oversight of your registered user base.",
  totalResults: "Registered users in system",
  analysis: "Analysis",
  dataUpdate: "Data Update",
  liveAnalytics: "Live Analytics",
  userAnalytics: "User Analytics",
  pageNotFound: "Page Not Found",
  pageNotFoundMsg:
    "Oops! The page you're looking for doesn't exist. It might have been moved or the URL might be incorrect.",
  backToDashboard: "Back to Dashboard",
  pageNotFoundMsg2:
    "If you think this is a mistake, please contact our support team.",
};
